In [1]:
import pandas as pd

In [2]:
# Coloque o arquivo "Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"
# na MESMA PASTA deste notebook para o caminho relativo abaixo funcionar.
# Se preferir, troque pelo caminho completo do arquivo no seu computador, ex:
# path = r"C:\Users\SeuUsuario\Documents\Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"
path = "Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

In [3]:
formacao_bruto = pd.read_excel(path, header=None)

In [4]:
formacao_bruto

                                                    0         1         2         3                                               4        5         6  \0   Tabela 10063 - Pessoas com nível superior comp...       NaN       NaN       NaN                                             NaN      NaN       NaN   1        Brasil, Grande Região e Unidade da Federação     Total       NaN       NaN  Ciência, Tecnologia, Engenharias e Matemática       NaN       NaN   2                                                 NaN     Total    Homens  Mulheres                                           Total   Homens  Mulheres   3                                              Brasil  25854291  10478534  15375757                                         4149041  2750422   1398619   4                                               Norte   1525166    590558    934609                                          209657   133055     76601   5                                            Nordeste   4748933   1744994   3003939                                          621388   389993    231395   6                                             Sudeste  12828829   5391638   7437191                                         2328122  1588874    739247   7                                                 Sul   4338861   1768855   2570005                                          662916   427372    235543   8                                        Centro-Oeste   2412502    982489   1430013                                          326959   211124    115834   9                                            Rondônia    164632     62766    101866                                           20538    11863      8675   10                                               Acre     84300     33291     51009                                           10364     6237      4128   11                                           Amazonas    342566    141059    201507                                           52669    34749     17919   12                                            Roraima     67045     25585     41460                                            8016     4958      3057   13                                               Pará    601096    229285    371811                                           86691    55481     31211   14                                              Amapá     89191     35085     54106                                           11349     7464      3885   15                                          Tocantins    176336     63485    112851                                           20028    12304      7724   16                                           Maranhão    468681    161352    307329                                           55068    33820     21248   17                                              Piauí    304955    108371    196584                                           37135    21668     15467   18                                              Ceará    759303    285013    474290                                           99062    63935     35126   19                                Rio Grande do Norte    339913    131178    208735                                           46857    30398     16459   20                                            Paraíba    390742    147221    243521                                           52223    33369     18855   21                                         Pernambuco    852481    321587    530893                                          120260    73253     47007   22                                            Alagoas    267996     98462    169534                                           33596    21398     12198   23                                            Sergipe    218255     80608    137646                                           29020    17596     11422   24                                              Bahia   1146608    411202    735406                                          148167    94556     53612   25                                       Minas Gerais   2615434   1031532   1583902                                          452258   291778    160479   26                                     Espírito Santo    491101    193756    297344                                           75667    49648     26018   27                                     Rio de Janeiro   2243707    942645   1301062                                          406529   265723    140805   28                                          São Paulo   7478587   3223705   4254883                                         1393668   981724    411944   29                                             Paraná   1687930    695425    992505                                          255635   166579     89056   30                                     Santa Catarina   1162515    489557    672958                                          185742   126554     59188   31                                  Rio Grande do Sul   1488416    583873    904542                                          221541   134240     87300   32                                 Mato Grosso do Sul    366249    145341    220908                                           46340    28241     18100   33                                        Mato Grosso    450264    173267    276997                                           56776    33307     23468   34                                              Goiás    879270    350828    528443                                          116867    74711     42156   35                                   Distrito Federal    716719    313054    403665                                          106976    74866     32109   36                    Fonte: IBGE - Censo Demográfico       NaN       NaN       NaN                                             NaN      NaN       NaN                                                    7        8         9  0                                              NaN      NaN       NaN  1   Educação, Serviços pessoais, Saúde e Bem-estar      NaN       NaN  2                                            Total   Homens  Mulheres  3                                          8079707  1677985   6401723  4                                           599785   141169    458616  5                                          1822087   363905   1458181  6                                          3652397   768288   2884108  7                                          1256291   248574   1007718  8                                           749148   156048    593101  9                                            63584    13963     49622  10                                           33379     9121     24258  11                                          121988    30738     91249  12                                           23977     5880     18098  13                                          248397    58128    190270  14                                           36754     9794     26960  15                                           71705    13548     58158  16                                          206222    40667    165555  17                                          128416    25959    102457  18                                          294578    64582    229996  19                                          135434    28273    107161  20                                          150862    30025    120837  21                                          281695    57333    224362  22                                          106971    20060     86911  23                                           83176    16801     66376  24                                          434735    80208    354528  25                                          832482   157960    674521  26                                          161332    29788    131544  27                                          612263   145864    466399  28                                         2046321   434677   1611645  29                                          501471    98191    403280  30                                          333537    67571    265964  31                                          421284    82812    338472  32                                          128352    26911    101443  33                                          141121    27052    114069  34                                          288616    56564    232052  35                                          191061    45521    145538  36                                             NaN      NaN       NaN

A tabela deverá ser dividida em 3
- homens e mulheres por região com curso superior
- homens e mulheres por região com curso nas áreas de Ciência, Tecnologia, Engenharias e Matemática
- homens e mulheres por região com curso nas áreas de Educação, Serviços pessoais, Saúde e Bem-estar

Exemplo 1 — Curso superior (todas as áreas)

In [5]:
# : = todas as linhas  |  0:4 = colunas 0, 1, 2 e 3 (as 4 primeiras)
formacao_total = formacao_bruto.iloc[3:36, 0:4].copy()

In [6]:
formacao_total.columns = [
    "uf_regiao",
    "total",
    "total_homens",
    "total_mulheres"
]

In [7]:
formacao_total

              uf_regiao     total total_homens total_mulheres3                Brasil  25854291     10478534       153757574                 Norte   1525166       590558         9346095              Nordeste   4748933      1744994        30039396               Sudeste  12828829      5391638        74371917                   Sul   4338861      1768855        25700058          Centro-Oeste   2412502       982489        14300139              Rondônia    164632        62766         10186610                 Acre     84300        33291          5100911             Amazonas    342566       141059         20150712              Roraima     67045        25585          4146013                 Pará    601096       229285         37181114                Amapá     89191        35085          5410615            Tocantins    176336        63485         11285116             Maranhão    468681       161352         30732917                Piauí    304955       108371         19658418                Ceará    759303       285013         47429019  Rio Grande do Norte    339913       131178         20873520              Paraíba    390742       147221         24352121           Pernambuco    852481       321587         53089322              Alagoas    267996        98462         16953423              Sergipe    218255        80608         13764624                Bahia   1146608       411202         73540625         Minas Gerais   2615434      1031532        158390226       Espírito Santo    491101       193756         29734427       Rio de Janeiro   2243707       942645        130106228            São Paulo   7478587      3223705        425488329               Paraná   1687930       695425         99250530       Santa Catarina   1162515       489557         67295831    Rio Grande do Sul   1488416       583873         90454232   Mato Grosso do Sul    366249       145341         22090833          Mato Grosso    450264       173267         27699734                Goiás    879270       350828         52844335     Distrito Federal    716719       313054         403665

In [8]:
formacao_total["percentual_mulheres"] = ((formacao_total['total_mulheres'] / formacao_total['total']) * 100).round(2)

In [9]:
formacao_total

              uf_regiao     total total_homens total_mulheres percentual_mulheres3                Brasil  25854291     10478534       15375757               59.474                 Norte   1525166       590558         934609               61.285              Nordeste   4748933      1744994        3003939               63.266               Sudeste  12828829      5391638        7437191               57.977                   Sul   4338861      1768855        2570005               59.238          Centro-Oeste   2412502       982489        1430013               59.289              Rondônia    164632        62766         101866               61.8710                 Acre     84300        33291          51009               60.5111             Amazonas    342566       141059         201507               58.8212              Roraima     67045        25585          41460               61.8413                 Pará    601096       229285         371811               61.8614                Amapá     89191        35085          54106               60.6615            Tocantins    176336        63485         112851                64.016             Maranhão    468681       161352         307329               65.5717                Piauí    304955       108371         196584               64.4618                Ceará    759303       285013         474290               62.4619  Rio Grande do Norte    339913       131178         208735               61.4120              Paraíba    390742       147221         243521               62.3221           Pernambuco    852481       321587         530893               62.2822              Alagoas    267996        98462         169534               63.2623              Sergipe    218255        80608         137646               63.0724                Bahia   1146608       411202         735406               64.1425         Minas Gerais   2615434      1031532        1583902               60.5626       Espírito Santo    491101       193756         297344               60.5527       Rio de Janeiro   2243707       942645        1301062               57.9928            São Paulo   7478587      3223705        4254883               56.8929               Paraná   1687930       695425         992505                58.830       Santa Catarina   1162515       489557         672958               57.8931    Rio Grande do Sul   1488416       583873         904542               60.7732   Mato Grosso do Sul    366249       145341         220908               60.3233          Mato Grosso    450264       173267         276997               61.5234                Goiás    879270       350828         528443                60.135     Distrito Federal    716719       313054         403665               56.32

**Leitura rápida do Exemplo 1:** no Brasil, mulheres já são **59,47%** dos formados no ensino superior (quase 6 em cada 10). Isso é maioria em todas as regiões — o Nordeste é onde essa maioria é mais forte (63,26%) e o Sudeste onde é mais fraca (57,97%), mas em nenhum lugar os homens ultrapassam as mulheres.

## Exemplo 2 — Ciência, Tecnologia, Engenharias e Matemática (STEM)

In [10]:
# : = todas as linhas | as colunas dessa área ficam nas posições 0 (uf/região), 4, 5 e 6
formacao_stem = formacao_bruto.iloc[3:36, [0, 4, 5, 6]].copy()

In [11]:
formacao_stem.columns = [
    "uf_regiao",
    "total",
    "total_homens",
    "total_mulheres"
]

In [12]:
formacao_stem

              uf_regiao    total total_homens total_mulheres3                Brasil  4149041      2750422        13986194                 Norte   209657       133055          766015              Nordeste   621388       389993         2313956               Sudeste  2328122      1588874         7392477                   Sul   662916       427372         2355438          Centro-Oeste   326959       211124         1158349              Rondônia    20538        11863           867510                 Acre    10364         6237           412811             Amazonas    52669        34749          1791912              Roraima     8016         4958           305713                 Pará    86691        55481          3121114                Amapá    11349         7464           388515            Tocantins    20028        12304           772416             Maranhão    55068        33820          2124817                Piauí    37135        21668          1546718                Ceará    99062        63935          3512619  Rio Grande do Norte    46857        30398          1645920              Paraíba    52223        33369          1885521           Pernambuco   120260        73253          4700722              Alagoas    33596        21398          1219823              Sergipe    29020        17596          1142224                Bahia   148167        94556          5361225         Minas Gerais   452258       291778         16047926       Espírito Santo    75667        49648          2601827       Rio de Janeiro   406529       265723         14080528            São Paulo  1393668       981724         41194429               Paraná   255635       166579          8905630       Santa Catarina   185742       126554          5918831    Rio Grande do Sul   221541       134240          8730032   Mato Grosso do Sul    46340        28241          1810033          Mato Grosso    56776        33307          2346834                Goiás   116867        74711          4215635     Distrito Federal   106976        74866          32109

In [13]:
formacao_stem["percentual_mulheres"] = ((formacao_stem['total_mulheres'] / formacao_stem['total']) * 100).round(2)

In [14]:
formacao_stem

              uf_regiao    total total_homens total_mulheres percentual_mulheres3                Brasil  4149041      2750422        1398619               33.714                 Norte   209657       133055          76601               36.545              Nordeste   621388       389993         231395               37.246               Sudeste  2328122      1588874         739247               31.757                   Sul   662916       427372         235543               35.538          Centro-Oeste   326959       211124         115834               35.439              Rondônia    20538        11863           8675               42.2410                 Acre    10364         6237           4128               39.8311             Amazonas    52669        34749          17919               34.0212              Roraima     8016         4958           3057               38.1413                 Pará    86691        55481          31211                36.014                Amapá    11349         7464           3885               34.2315            Tocantins    20028        12304           7724               38.5716             Maranhão    55068        33820          21248               38.5917                Piauí    37135        21668          15467               41.6518                Ceará    99062        63935          35126               35.4619  Rio Grande do Norte    46857        30398          16459               35.1320              Paraíba    52223        33369          18855                36.121           Pernambuco   120260        73253          47007               39.0922              Alagoas    33596        21398          12198               36.3123              Sergipe    29020        17596          11422               39.3624                Bahia   148167        94556          53612               36.1825         Minas Gerais   452258       291778         160479               35.4826       Espírito Santo    75667        49648          26018               34.3827       Rio de Janeiro   406529       265723         140805               34.6428            São Paulo  1393668       981724         411944               29.5629               Paraná   255635       166579          89056               34.8430       Santa Catarina   185742       126554          59188               31.8731    Rio Grande do Sul   221541       134240          87300               39.4132   Mato Grosso do Sul    46340        28241          18100               39.0633          Mato Grosso    56776        33307          23468               41.3334                Goiás   116867        74711          42156               36.0735     Distrito Federal   106976        74866          32109               30.02

**Leitura rápida do Exemplo 2:** em Ciência, Tecnologia, Engenharias e Matemática o quadro se inverte — as mulheres caem para **33,71%** dos formados no Brasil, ou seja, são minoria em todas as regiões. O Sudeste tem a menor participação feminina (31,75%) e o Nordeste a maior (37,24%), mas nenhuma região chega perto dos 50%.

## Exemplo 3 — Educação, Serviços pessoais, Saúde e Bem-estar

In [15]:
# : = todas as linhas | as colunas dessa área ficam nas posições 0 (uf/região), 7, 8 e 9
formacao_saude = formacao_bruto.iloc[3:36, [0, 7, 8, 9]].copy()

In [16]:
formacao_saude.columns = [
    "uf_regiao",
    "total",
    "total_homens",
    "total_mulheres"
]

In [17]:
formacao_saude

              uf_regiao    total total_homens total_mulheres3                Brasil  8079707      1677985        64017234                 Norte   599785       141169         4586165              Nordeste  1822087       363905        14581816               Sudeste  3652397       768288        28841087                   Sul  1256291       248574        10077188          Centro-Oeste   749148       156048         5931019              Rondônia    63584        13963          4962210                 Acre    33379         9121          2425811             Amazonas   121988        30738          9124912              Roraima    23977         5880          1809813                 Pará   248397        58128         19027014                Amapá    36754         9794          2696015            Tocantins    71705        13548          5815816             Maranhão   206222        40667         16555517                Piauí   128416        25959         10245718                Ceará   294578        64582         22999619  Rio Grande do Norte   135434        28273         10716120              Paraíba   150862        30025         12083721           Pernambuco   281695        57333         22436222              Alagoas   106971        20060          8691123              Sergipe    83176        16801          6637624                Bahia   434735        80208         35452825         Minas Gerais   832482       157960         67452126       Espírito Santo   161332        29788         13154427       Rio de Janeiro   612263       145864         46639928            São Paulo  2046321       434677        161164529               Paraná   501471        98191         40328030       Santa Catarina   333537        67571         26596431    Rio Grande do Sul   421284        82812         33847232   Mato Grosso do Sul   128352        26911         10144333          Mato Grosso   141121        27052         11406934                Goiás   288616        56564         23205235     Distrito Federal   191061        45521         145538

In [18]:
formacao_saude["percentual_mulheres"] = ((formacao_saude['total_mulheres'] / formacao_saude['total']) * 100).round(2)

In [19]:
formacao_saude

              uf_regiao    total total_homens total_mulheres percentual_mulheres3                Brasil  8079707      1677985        6401723               79.234                 Norte   599785       141169         458616               76.465              Nordeste  1822087       363905        1458181               80.036               Sudeste  3652397       768288        2884108               78.967                   Sul  1256291       248574        1007718               80.218          Centro-Oeste   749148       156048         593101               79.179              Rondônia    63584        13963          49622               78.0410                 Acre    33379         9121          24258               72.6711             Amazonas   121988        30738          91249                74.812              Roraima    23977         5880          18098               75.4813                 Pará   248397        58128         190270                76.614                Amapá    36754         9794          26960               73.3515            Tocantins    71705        13548          58158               81.1116             Maranhão   206222        40667         165555               80.2817                Piauí   128416        25959         102457               79.7918                Ceará   294578        64582         229996               78.0819  Rio Grande do Norte   135434        28273         107161               79.1220              Paraíba   150862        30025         120837                80.121           Pernambuco   281695        57333         224362               79.6522              Alagoas   106971        20060          86911               81.2523              Sergipe    83176        16801          66376                79.824                Bahia   434735        80208         354528               81.5525         Minas Gerais   832482       157960         674521               81.0326       Espírito Santo   161332        29788         131544               81.5427       Rio de Janeiro   612263       145864         466399               76.1828            São Paulo  2046321       434677        1611645               78.7629               Paraná   501471        98191         403280               80.4230       Santa Catarina   333537        67571         265964               79.7431    Rio Grande do Sul   421284        82812         338472               80.3432   Mato Grosso do Sul   128352        26911         101443               79.0333          Mato Grosso   141121        27052         114069               80.8334                Goiás   288616        56564         232052                80.435     Distrito Federal   191061        45521         145538               76.17

**Leitura rápida do Exemplo 3:** em Educação, Serviços pessoais, Saúde e Bem-estar as mulheres são amplamente maioria: **79,23%** dos formados no Brasil, chegando a **80,21%** no Sul e **80,03%** no Nordeste — as duas maiores concentrações do país.

## Comparando as três áreas

In [20]:
# Junta o "% de mulheres" das três tabelas em uma só, por região, para comparar lado a lado
comparacao = formacao_total[["uf_regiao", "percentual_mulheres"]].rename(
    columns={"percentual_mulheres": "pct_mulheres_total"}
)
comparacao = comparacao.merge(
    formacao_stem[["uf_regiao", "percentual_mulheres"]].rename(
        columns={"percentual_mulheres": "pct_mulheres_stem"}
    ),
    on="uf_regiao"
)
comparacao = comparacao.merge(
    formacao_saude[["uf_regiao", "percentual_mulheres"]].rename(
        columns={"percentual_mulheres": "pct_mulheres_saude"}
    ),
    on="uf_regiao"
)

# Só as grandes regiões + Brasil, para facilitar a leitura
comparacao_regioes = comparacao[comparacao["uf_regiao"].isin(
    ["Brasil", "Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]
)].reset_index(drop=True)

comparacao_regioes

      uf_regiao pct_mulheres_total pct_mulheres_stem pct_mulheres_saude0        Brasil              59.47             33.71              79.231         Norte              61.28             36.54              76.462      Nordeste              63.26             37.24              80.033       Sudeste              57.97             31.75              78.964           Sul              59.23             35.53              80.215  Centro-Oeste              59.28             35.43              79.17

In [21]:
brasil = comparacao.loc[comparacao["uf_regiao"] == "Brasil"].iloc[0]

print("Brasil — % de mulheres entre os formados, por área de curso")print(f"  Curso superior (geral):                     {brasil.pct_mulheres_total}%")print(f"  Ciência, Tecnologia, Eng. e Matemática:      {brasil.pct_mulheres_stem}%")print(f"  Educação, Serviços pessoais e Saúde:         {brasil.pct_mulheres_saude}%")

Brasil — % de mulheres entre os formados, por área de curso
  Curso superior (geral):                     59.47%
  Ciência, Tecnologia, Eng. e Matemática:      33.71%
  Educação, Serviços pessoais e Saúde:         79.23%

**Conclusão:** no ensino superior como um todo as mulheres já são maioria (quase 6 em cada 10 formados). Mas essa maioria não se distribui igualmente entre as áreas: elas são **minoria** em Ciência, Tecnologia, Engenharias e Matemática (1 em cada 3) e **super-representadas** em Educação, Serviços pessoais e Saúde (quase 8 em cada 10) — um padrão de segregação de gênero por área de formação que se repete em todas as regiões do país.